org: internal
space: eHandbook-api
space-developer:
  users:
  - jenkins-sa
space-auditor:
  saml_group:
  - entra-id-platform-users        # TODO: confirm actual Entra ID group name
isolation-segment: isolated-segment
enable-security-group: false
named-security-groups:
- SQL-ACCESS-ASG                   # backend/API tier only
